# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BasicInfoGatherer
                                 A QGIS plugin
 Gathers basic information about sites
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-27
        copyright            : (C) 2022 by David Gibbons
        email                : david@gibbons.digital
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BasicInfoGatherer class from file BasicInfoGatherer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .info_gather import BasicInfoGatherer
    return BasicInfoGatherer(iface)
